(part "1514-2"
    (packageRef "15142")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "534-1514-2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/1514-2?qs=q0tsjPZWdm8tT%252BQidGxCiw%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "1514-2")
    (property "Description" "KEYSTONE - 1514-2 - TERMINAL, TURRET, 0.09IN, THROUGH HOLE")
    (property "Datasheet_Link" "")
    (property "symbolName1" "1514-2")
)
